<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Data_Analytics_3_Pandasindepth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
frame = pd.DataFrame({'id':['A','B','C','D','E'],'price':[11,12,13,14,15]})

In [3]:
frame

  id  price
0  A     11
1  B     12
2  C     13
3  D     14
4  E     15

In [4]:
frame2 = pd.DataFrame( {'id': ['A','B','C','D'],
                        'color':['white','red','red','black']})
frame2

  id  color
0  A  white
1  B    red
2  C    red
3  D  black

In [5]:
pd.merge(frame,frame2)

  id  price  color
0  A     11  white
1  B     12    red
2  C     13    red
3  D     14  black

We can also give arg -> on = 'Column name' in merge() , it can be either a list or individual features

In [6]:
frame1 = pd.DataFrame( {'id': ['ball','pencil','pen',',mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','PPOD']})
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [7]:
pd.merge(frame1,frame2,on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [8]:
pd.merge(frame1,frame2,left_on='id',right_on='brand')

Empty DataFrame
Columns: [id_x, color, brand_x, id_y, brand_y]
Index: []

In [9]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
array2 = np.arange(9).reshape((3,3))
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.concatenate(array1,array2)

TypeError: ignored

In [15]:
frame1.stack()

0  id          ball
   color      white
   brand        OMG
1  id        pencil
   color        red
   brand        ABC
2  id           pen
   color        red
   brand        ABC
3  id          ,mug
   color      black
   brand        POD
4  id       ashtray
   color      green
   brand       PPOD
dtype: object

In [16]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3     ,mug  black   POD
4  ashtray  green  PPOD

In [17]:
result = [23,26,75,24,75,25,74,325,6,3,225,63]
bins = [0,15,30,45,60,75,90,105]
pd.cut(result,bins)

[(15, 30], (15, 30], (60, 75], (15, 30], (60, 75], ..., NaN, (0.0, 15.0], (0.0, 15.0], NaN, (60.0, 75.0]]
Length: 12
Categories (7, interval[int64, right]): [(0, 15] < (15, 30] < (30, 45] < (45, 60] < (60, 75] <
                                         (75, 90] < (90, 105]]

In [20]:
pd.cut(result,bins).value_counts()

(0, 15]      2
(15, 30]     4
(30, 45]     0
(45, 60]     0
(60, 75]     4
(75, 90]     0
(90, 105]    0
dtype: int64

In [22]:
bin_names = ['likely','unlikely','highly likely','a','b','c','d']
pd.cut(result,bins,labels=bin_names)

['unlikely', 'unlikely', 'b', 'unlikely', 'b', ..., NaN, 'likely', 'likely', NaN, 'b']
Length: 12
Categories (7, object): ['likely' < 'unlikely' < 'highly likely' < 'a' < 'b' < 'c' < 'd']

In [28]:
randframe = pd.DataFrame(np.random.randn(3,3))

In [30]:
randframe.describe()

              0         1         2
count  3.000000  3.000000  3.000000
mean   0.044987 -0.080963 -0.046325
std    0.867687  0.121874  0.278914
min   -0.768466 -0.201376 -0.363107
25%   -0.411655 -0.142604 -0.150668
50%   -0.054843 -0.083832  0.061771
75%    0.451714 -0.020756  0.112066
max    0.958271  0.042321  0.162362

In [31]:
randframe.std()

0    0.867687
1    0.121874
2    0.278914
dtype: float64

In [38]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [40]:
sample = np.random.randint(0, len(randframe), size=3)
sample

array([1, 2, 2])

In [42]:
randframe.take(sample)

          0         1         2
1  0.958271  0.042321 -0.363107
2 -0.054843 -0.083832  0.162362
2 -0.054843 -0.083832  0.162362